### ISSUE TITLE
Error detected while processing function ag#Ag

### ISSUE THREAD

**Issue by Doppp** [rking/ag.vim#57]
Ag works fine every now and then but then it breaks. It also always breaks for the same search strings.

![screen shot 2014-05-21 at 4 26 03 pm](https://cloud.githubusercontent.com/assets/627410/3048023/5866e226-e13f-11e3-817a-fc0f256cbc3c.png)

**Comment by raine** [comment]
Any alternative to ag.vim that doesn't have this issue?

**Comment by losingkeys** [comment]
You could try https://github.com/mileszs/ack.vim with `let g:ackprg="ag"`, though I'm not positive that'll work (it's been awhile since this wrapper was forked from ack.vim). Also this wrapper has some ag-specific commands, so you'd lose those.

I think https://github.com/rking/ag.vim/commit/e70e049bfd1f4dce1d55881c4eee3e4320121cfc fixes this issue (by ignoring errors generated by the search command), but I'm reopening this issue until we know for sure this is the fix, so the issue doesn't fall through the cracks.

@raine  @deeTEEcee @troygoode @sirbrillig @dpdawson @mrfletch @srcoley @wjakob @Doppp: mind updating your copy of this plugin and checking if this fixes your issue or not?

**Comment by raine** [comment]
Thanks. I'm giving it a go and will report back.

**Comment by raine** [comment]
The error is gone but the weird behavior remains. 

You just get no results until you press enter and then it opens some file as read-only.
