### ISSUE TITLE
glitch with search results & quickfix window

### ISSUE THREAD

**Issue by troygoode** [rking/ag.vim#69]
_Related to https://github.com/rking/ag.vim/issues/57#issuecomment-60670223 and https://github.com/rking/ag.vim/issues/58._

There is currently a bug that introduces some wonkiness with getting the search results to show within the quickfix window. Here is the issue:
- The first time I run `:Ag example` the search is run (in the background), the first result is automatically opened, the quickfix window is _not_ opened, and the status bar says `No matches for "example"`.
- While on a file **that is also the first result of the search you're about to execute** running `:Ag example` will now correctly open the quickfix window, but now when you load one of the results into a buffer with `o` the quickfix window's results are cleared away.

I am using Square's [maximum-awesome](https://github.com/square/maximum-awesome) plugin set ([default bundles here](https://github.com/square/maximum-awesome/blob/master/vimrc.bundles)) on OS X Yosemite with vim 7.4.52.

Here are some screenshots illustrating the above:

![screenshot 2014-11-02 10 55 51](https://cloud.githubusercontent.com/assets/72844/4876386/c786f6d2-62c2-11e4-943f-530105cc6d20.png)
![screenshot 2014-11-02 10 55 54](https://cloud.githubusercontent.com/assets/72844/4876387/ca1b942a-62c2-11e4-956f-dfff41c4d751.png)
![screenshot 2014-11-02 10 55 59](https://cloud.githubusercontent.com/assets/72844/4876388/cd5377fc-62c2-11e4-8a50-5a0de921e727.png)
![screenshot 2014-11-02 10 56 03](https://cloud.githubusercontent.com/assets/72844/4876389/cff046d4-62c2-11e4-8690-817d88a258b9.png)
![screenshot 2014-11-02 10 56 17](https://cloud.githubusercontent.com/assets/72844/4876390/d2cc5a82-62c2-11e4-80a9-26fd6d082874.png)

**Comment by amarshall** [comment]
I’m seeing this issue too. I’ve managed to find what appears to be the culprit in a broad sense: using the [jshint.vim](https://github.com/wookiehangover/jshint.vim/tree/67af059d15ab0548dd3f55a6a77e966c47615dde) plugin when the ag.vim search results include JavaScript files causes this behavior to occur. Note that this same behavior occurs with the ack.vim plugin & `:Ack` instead of `:Ag`.

Having only the jshint.vim + ag/ack.vim plugins exposes the issue, and removing only the jshint.vim plugin resolves it. I’m not sure what in there is causing it, but it’s at least a starting point.

**Comment by amarshall** [comment]
It seems to be that jshint.vim runs when entering the buffer by default, so if the *first* result is a JavaScript file, then ag.vim opens it, jshint.vim runs and populates the quickfix list with its errors (with are none in most cases), overriding the quickfix list that ag.vim just populated.

**Comment by tomauty** [comment]
Nice find. Thanks for that.
